name: oc
services:
  dev-edk2-docs:
    extends:
      file: docker-compose.yaml
      service: dev-docs
    build:
      args:
        OC_DEV_DOCS_BASE: oc-dev-edk2
      tags:
        - "oc-dev-edk2-docs"
    volumes:
      - .:/com.docker.devenvironments.code
    entrypoint:
      - sleep
      - infinity
